### ISSUE TITLE
GPG missing for SOPS

### ISSUE THREAD

**Issue by MarcPerezPro** [devops-infra/docker-terragrunt#2077]
## :memo:  Brief description

I'm using this image in my CI/CD system (GitLab CI) to deploy using Terragrunt. I'm encountering 2 problems:
1. To use `sops_decrypt_file` in Terragrunt, I need to install gnupg to run  `echo "$SOPS_GPG_PRIVATE_KEY" | gpg --import`.
2. I can't install GPG due to `apt-get update` giving me errors like
```txt
E: The repository 'http://archive.ubuntu.com/ubuntu jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy-updates InRelease: At least one invalid signature was encountered.
```
but I can't run `apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 76F1A20FF987672F` due to `E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation`.
It's a catch 22 because I'm trying to install GPG.

Here is my workaround, but it's unsecure:
```yaml
deploy_prod:
  stage: deploy
  image: devopsinfra/docker-terragrunt:slim-tf-1.7.5-tg-0.55.20
  before_script:
    - sed -i 's|^deb |deb [trusted=yes] |' /etc/apt/sources.list
    - apt-get update && apt-get install gnupg -y
    - echo "$SOPS_GPG_PRIVATE_KEY" | gpg --import
  script:
    - cd terraform/env/prod
    - terragrunt run-all apply --terragrunt-non-interactive
  only:
    - main
  ```

## :bulb: Proposed Solution

Preinstall GPG in the Docker image by adding `apt-get install gnupg -y` somewhere in the Dockerfile.

## :warning: Checklist
* [x] Provided a clear and concise description of what the issue is.
* [x] Given a clear and concise description of what is expected.
* [ ] Proposed a clear and concise description of any alternative solutions or other features.
* [x] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md
